const ADD_USER = 'ADD_USER'
const GET_USERS = 'GRT_USERS'
const GET_ERROR_USER_DATA = 'GRT_ERROR_USER_DATA'
const GET_USER_DATA = 'GET_USER_DATA'

export {
    ADD_USER,
    GET_USERS,
    GET_USER_DATA,
    GET_ERROR_USER_DATA
}
